apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/crd/overlays/stonesoup
- ../../base/gitops-namespace
- ../../../appstudio-controller/config/default-no-prometheus
# TODO: GITOPSRVCE-440: Remove '-no-webhook' from this line:
- ../../../backend/config/default-no-webhook-no-prometheus
- ../../../cluster-agent/config/default-no-prometheus
- ../../base/gitops-service-argocd/base
- ../appstudio-staging-cluster/prometheus

patchesStrategicMerge:
- backend-deployment-patch.yaml
- cluster-agent-deployment-patch.yaml
- appstudio-controller-deployment-patch.yaml

# Uncomment to use a custom image:
# images:
#   - name: \${COMMON_IMAGE}
#     newName: quay.io/(your user name)/gitops-service
#     newTag: latest
