apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/crd/overlays/local-dev
- ../../base/gitops-namespace
- ../../../appstudio-controller/config/default
# TODO: GITOPSRVCE-440: Remove '-no-webhook' from this line:
- ../../../backend/config/default-no-webhook
- ../../../cluster-agent/config/default
- ../../base/postgresql-staging
# - ../../base/gitops-service-argocd

# Uncomment to use a custom image:

# images:
#   - name: \${COMMON_IMAGE}
#     newName: quay.io/(your user name)/gitops-service
#     newTag: latest
