apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: purple-mermaid-app
  namespace: jane
#  finalizers:
#    - application.appstudio.redhat.com/finalizer
spec:
  appModelRepository:
    url: ''
  displayName: Purple Mermaid app
  gitOpsRepository:
    url: ''
status:
  conditions: []
  devfile: |
    metadata:
      attributes:
        appModelRepository.context: /
        appModelRepository.url: https://github.com/redhat-appstudio-appdata/test-application-rorai-concentrate-complete
        gitOpsRepository.context: /
        gitOpsRepository.url: https://github.com/redhat-appstudio-appdata/test-application-rorai-concentrate-complete
      name: Test Application
    projects:
    - git:
        remotes:
          origin: https://github.com/devfile-samples/devfile-sample-code-with-quarkus
      name: java-quarkus
    schemaVersion: 2.1.0

