# permissions for end users to edit gitopsdeploymentrepositorycredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitopsdeploymentrepositorycredential-editor-role
rules:
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentrepositorycredentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentrepositorycredentials/status
  verbs:
  - get
