# permissions for end users to view gitopsdeploymentmanagedenvironments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitopsdeploymentmanagedenvironment-viewer-role
rules:
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentmanagedenvironments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentmanagedenvironments/status
  verbs:
  - get
